# permissions for end users to view watchmanstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watchmanstatus-viewer-role
rules:
- apiGroups:
  - core.openfeature.dev
  resources:
  - watchmanstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.openfeature.dev
  resources:
  - watchmanstatuses/status
  verbs:
  - get
