# permissions for end users to edit watchmanstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watchmanstatus-editor-role
rules:
- apiGroups:
  - core.openfeature.dev
  resources:
  - watchmanstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openfeature.dev
  resources:
  - watchmanstatuses/status
  verbs:
  - get
